export type ScoringBlock = "RESULT" | "EFFICIENCY" | "QUALITY";

export type CriterionInputMode = "number" | "percent" | "satisfaction";

export interface CriterionTemplate {
  groupCode: string;
  block: ScoringBlock;
  code: string;
  label: string;
  unit: string;
  benchmarkMax: number;
  weight: number;
  inputMode: CriterionInputMode;
  helpText: string;
  autoCalculated: boolean;
  /** If false, value is stored for formulas but omitted from the normalized score breakdown (e.g. intermediate counts). */
  includeInBreakdown?: boolean;
}

export const SCORING_TEMPLATES: CriterionTemplate[] = [
  // ---------- Группа A — ДК ----------
  {
    groupCode: "A",
    block: "RESULT",
    code: "attendance",
    label: "Посещаемость",
    unit: "чел.",
    benchmarkMax: 8000,
    weight: 0.4,
    inputMode: "number",
    helpText: "Суммарное число посещений за период.",
    autoCalculated: false,
  },
  {
    groupCode: "A",
    block: "RESULT",
    code: "eventsCount",
    label: "Количество мероприятий",
    unit: "ед.",
    benchmarkMax: 50,
    weight: 0.3,
    inputMode: "number",
    helpText: "Число проведённых мероприятий.",
    autoCalculated: false,
  },
  {
    groupCode: "A",
    block: "RESULT",
    code: "clubFormations",
    label: "Клубные формирования",
    unit: "ед.",
    benchmarkMax: 25,
    weight: 0.3,
    inputMode: "number",
    helpText: "Количество стабильных клубных формирований.",
    autoCalculated: false,
  },
  {
    groupCode: "A",
    block: "RESULT",
    code: "childEventsCount",
    label: "Детские мероприятия (кол-во)",
    unit: "ед.",
    benchmarkMax: 50,
    weight: 0,
    inputMode: "number",
    helpText: "Сколько мероприятий из общего числа адресовано детской аудитории. Доля в % считается автоматически.",
    autoCalculated: false,
    includeInBreakdown: false,
  },
  {
    groupCode: "A",
    block: "EFFICIENCY",
    code: "attendancePer100m2",
    label: "Посещаемость на 100 м²",
    unit: "чел./100 м²",
    benchmarkMax: 200,
    weight: 0.4,
    inputMode: "number",
    helpText: "Авто: посещаемость ÷ площадь × 100.",
    autoCalculated: true,
  },
  {
    groupCode: "A",
    block: "EFFICIENCY",
    code: "attendancePerStaff",
    label: "Посещаемость на ставку",
    unit: "чел./ставка",
    benchmarkMax: 500,
    weight: 0.3,
    inputMode: "number",
    helpText: "Авто: посещаемость ÷ число штатных ставок.",
    autoCalculated: true,
  },
  {
    groupCode: "A",
    block: "EFFICIENCY",
    code: "childEventsSharePct",
    label: "Доля детских мероприятий",
    unit: "%",
    benchmarkMax: 80,
    weight: 0.3,
    inputMode: "percent",
    helpText: "Авто: (детские мероприятия ÷ все мероприятия) × 100; при нуле мероприятий — 0%.",
    autoCalculated: true,
  },
  {
    groupCode: "A",
    block: "QUALITY",
    code: "satisfaction",
    label: "Удовлетворённость",
    unit: "балл",
    benchmarkMax: 5,
    weight: 0.5,
    inputMode: "satisfaction",
    helpText: "Средняя оценка удовлетворённости по шкале до 5.",
    autoCalculated: false,
  },
  {
    groupCode: "A",
    block: "QUALITY",
    code: "newFormats",
    label: "Новые форматы",
    unit: "ед.",
    benchmarkMax: 5,
    weight: 0.3,
    inputMode: "number",
    helpText: "Число новых форматов работы с аудиторией.",
    autoCalculated: false,
  },
  {
    groupCode: "A",
    block: "QUALITY",
    code: "coveragePct",
    label: "Охват населения",
    unit: "%",
    benchmarkMax: 60,
    weight: 0.2,
    inputMode: "percent",
    helpText: "Авто: посещаемость ÷ численность в зоне × 100.",
    autoCalculated: true,
  },

  // ---------- Группа B — библиотеки ----------
  {
    groupCode: "B",
    block: "RESULT",
    code: "attendance",
    label: "Посещаемость",
    unit: "чел.",
    benchmarkMax: 2000,
    weight: 0.4,
    inputMode: "number",
    helpText: "Суммарное число посещений.",
    autoCalculated: false,
  },
  {
    groupCode: "B",
    block: "RESULT",
    code: "eventsCount",
    label: "Мероприятия",
    unit: "ед.",
    benchmarkMax: 20,
    weight: 0.3,
    inputMode: "number",
    helpText: "Количество мероприятий.",
    autoCalculated: false,
  },
  {
    groupCode: "B",
    block: "RESULT",
    code: "bookLoans",
    label: "Книговыдачи",
    unit: "ед.",
    benchmarkMax: 5000,
    weight: 0.3,
    inputMode: "number",
    helpText: "Число выданных экземпляров.",
    autoCalculated: false,
  },
  {
    groupCode: "B",
    block: "EFFICIENCY",
    code: "attendancePer100m2",
    label: "Посещаемость на 100 м²",
    unit: "чел./100 м²",
    benchmarkMax: 500,
    weight: 0.4,
    inputMode: "number",
    helpText: "Авто: посещаемость ÷ площадь × 100.",
    autoCalculated: true,
  },
  {
    groupCode: "B",
    block: "EFFICIENCY",
    code: "attendancePerStaff",
    label: "Посещаемость на ставку",
    unit: "чел./ставка",
    benchmarkMax: 400,
    weight: 0.3,
    inputMode: "number",
    helpText: "Авто: посещаемость ÷ число штатных ставок.",
    autoCalculated: true,
  },
  {
    groupCode: "B",
    block: "EFFICIENCY",
    code: "readersCount",
    label: "Читатели",
    unit: "чел.",
    benchmarkMax: 800,
    weight: 0.3,
    inputMode: "number",
    helpText: "Количество активных читателей.",
    autoCalculated: false,
  },
  {
    groupCode: "B",
    block: "QUALITY",
    code: "satisfaction",
    label: "Удовлетворённость",
    unit: "балл",
    benchmarkMax: 5,
    weight: 0.5,
    inputMode: "satisfaction",
    helpText: "Средняя оценка до 5 баллов.",
    autoCalculated: false,
  },
  {
    groupCode: "B",
    block: "QUALITY",
    code: "digitalServicesCount",
    label: "Цифровые сервисы",
    unit: "ед.",
    benchmarkMax: 50,
    weight: 0.3,
    inputMode: "number",
    helpText: "Количество доступных цифровых сервисов.",
    autoCalculated: false,
  },
  {
    groupCode: "B",
    block: "QUALITY",
    code: "coveragePct",
    label: "Охват населения",
    unit: "%",
    benchmarkMax: 50,
    weight: 0.2,
    inputMode: "percent",
    helpText: "Авто: посещаемость ÷ численность в зоне × 100.",
    autoCalculated: true,
  },

  // ---------- Группа V — музеи ----------
  {
    groupCode: "V",
    block: "RESULT",
    code: "attendance",
    label: "Посещаемость",
    unit: "чел.",
    benchmarkMax: 1500,
    weight: 0.4,
    inputMode: "number",
    helpText: "Суммарное число посещений.",
    autoCalculated: false,
  },
  {
    groupCode: "V",
    block: "RESULT",
    code: "excursionsCount",
    label: "Экскурсии",
    unit: "ед.",
    benchmarkMax: 30,
    weight: 0.3,
    inputMode: "number",
    helpText: "Количество проведённых экскурсий.",
    autoCalculated: false,
  },
  {
    groupCode: "V",
    block: "RESULT",
    code: "exhibitionsCount",
    label: "Выставки",
    unit: "ед.",
    benchmarkMax: 5,
    weight: 0.3,
    inputMode: "number",
    helpText: "Число выставочных проектов.",
    autoCalculated: false,
  },
  {
    groupCode: "V",
    block: "EFFICIENCY",
    code: "attendancePer100m2",
    label: "Посещаемость на 100 м²",
    unit: "чел./100 м²",
    benchmarkMax: 150,
    weight: 0.4,
    inputMode: "number",
    helpText: "Авто: посещаемость ÷ площадь × 100.",
    autoCalculated: true,
  },
  {
    groupCode: "V",
    block: "EFFICIENCY",
    code: "attendancePerStaff",
    label: "Посещаемость на ставку",
    unit: "чел./ставка",
    benchmarkMax: 200,
    weight: 0.3,
    inputMode: "number",
    helpText: "Авто: посещаемость ÷ число штатных ставок.",
    autoCalculated: true,
  },
  {
    groupCode: "V",
    block: "EFFICIENCY",
    code: "newFundItems",
    label: "Поступления в фонд",
    unit: "ед.",
    benchmarkMax: 30,
    weight: 0.3,
    inputMode: "number",
    helpText: "Новые единицы хранения за период.",
    autoCalculated: false,
  },
  {
    groupCode: "V",
    block: "QUALITY",
    code: "satisfaction",
    label: "Удовлетворённость",
    unit: "балл",
    benchmarkMax: 5,
    weight: 0.5,
    inputMode: "satisfaction",
    helpText: "Средняя оценка до 5 баллов.",
    autoCalculated: false,
  },
  {
    groupCode: "V",
    block: "QUALITY",
    code: "newExhibitsSharePct",
    label: "Доля новых экспозиций",
    unit: "%",
    benchmarkMax: 30,
    weight: 0.3,
    inputMode: "percent",
    helpText: "Доля обновлённых экспозиций в общем портфеле.",
    autoCalculated: false,
  },
  {
    groupCode: "V",
    block: "QUALITY",
    code: "coveragePct",
    label: "Охват населения",
    unit: "%",
    benchmarkMax: 30,
    weight: 0.2,
    inputMode: "percent",
    helpText: "Авто: посещаемость ÷ численность в зоне × 100.",
    autoCalculated: true,
  },

  // ---------- Группа G — КСЦ ----------
  {
    groupCode: "G",
    block: "RESULT",
    code: "attendance",
    label: "Посещаемость",
    unit: "чел.",
    benchmarkMax: 3000,
    weight: 0.4,
    inputMode: "number",
    helpText: "Суммарное число посещений.",
    autoCalculated: false,
  },
  {
    groupCode: "G",
    block: "RESULT",
    code: "eventsCount",
    label: "Мероприятия",
    unit: "ед.",
    benchmarkMax: 25,
    weight: 0.3,
    inputMode: "number",
    helpText: "Количество мероприятий.",
    autoCalculated: false,
  },
  {
    groupCode: "G",
    block: "RESULT",
    code: "sectionsCount",
    label: "Секции и кружки",
    unit: "ед.",
    benchmarkMax: 15,
    weight: 0.3,
    inputMode: "number",
    helpText: "Число действующих секций.",
    autoCalculated: false,
  },
  {
    groupCode: "G",
    block: "EFFICIENCY",
    code: "attendancePer100m2",
    label: "Посещаемость на 100 м²",
    unit: "чел./100 м²",
    benchmarkMax: 200,
    weight: 0.4,
    inputMode: "number",
    helpText: "Авто: посещаемость ÷ площадь × 100.",
    autoCalculated: true,
  },
  {
    groupCode: "G",
    block: "EFFICIENCY",
    code: "attendancePerStaff",
    label: "Посещаемость на ставку",
    unit: "чел./ставка",
    benchmarkMax: 300,
    weight: 0.3,
    inputMode: "number",
    helpText: "Авто: посещаемость ÷ число штатных ставок.",
    autoCalculated: true,
  },
  {
    groupCode: "G",
    block: "EFFICIENCY",
    code: "sportsEventsCount",
    label: "Спортивные мероприятия",
    unit: "ед.",
    benchmarkMax: 10,
    weight: 0.3,
    inputMode: "number",
    helpText: "Количество спортивных событий.",
    autoCalculated: false,
  },
  {
    groupCode: "G",
    block: "QUALITY",
    code: "satisfaction",
    label: "Удовлетворённость",
    unit: "балл",
    benchmarkMax: 5,
    weight: 0.5,
    inputMode: "satisfaction",
    helpText: "Средняя оценка до 5 баллов.",
    autoCalculated: false,
  },
  {
    groupCode: "G",
    block: "QUALITY",
    code: "gymAttendance",
    label: "Посещаемость залов",
    unit: "чел.",
    benchmarkMax: 3000,
    weight: 0.3,
    inputMode: "number",
    helpText: "Посещения спортивных зон.",
    autoCalculated: false,
  },
  {
    groupCode: "G",
    block: "QUALITY",
    code: "coveragePct",
    label: "Охват населения",
    unit: "%",
    benchmarkMax: 25,
    weight: 0.2,
    inputMode: "percent",
    helpText: "Авто: посещаемость ÷ численность в зоне × 100.",
    autoCalculated: true,
  },

  // ---------- Группа D — спорт ----------
  {
    groupCode: "D",
    block: "RESULT",
    code: "attendance",
    label: "Посещаемость",
    unit: "чел.",
    benchmarkMax: 2500,
    weight: 0.4,
    inputMode: "number",
    helpText: "Суммарное число посещений.",
    autoCalculated: false,
  },
  {
    groupCode: "D",
    block: "RESULT",
    code: "trainingsCount",
    label: "Тренировки",
    unit: "ед.",
    benchmarkMax: 100,
    weight: 0.3,
    inputMode: "number",
    helpText: "Количество проведённых тренировок.",
    autoCalculated: false,
  },
  {
    groupCode: "D",
    block: "RESULT",
    code: "sectionsCount",
    label: "Секции",
    unit: "ед.",
    benchmarkMax: 15,
    weight: 0.3,
    inputMode: "number",
    helpText: "Число спортивных секций.",
    autoCalculated: false,
  },
  {
    groupCode: "D",
    block: "EFFICIENCY",
    code: "attendancePer100m2",
    label: "Посещаемость на 100 м²",
    unit: "чел./100 м²",
    benchmarkMax: 250,
    weight: 0.4,
    inputMode: "number",
    helpText: "Авто: посещаемость ÷ площадь × 100.",
    autoCalculated: true,
  },
  {
    groupCode: "D",
    block: "EFFICIENCY",
    code: "attendancePerStaff",
    label: "Посещаемость на ставку",
    unit: "чел./ставка",
    benchmarkMax: 250,
    weight: 0.3,
    inputMode: "number",
    helpText: "Авто: посещаемость ÷ число штатных ставок.",
    autoCalculated: true,
  },
  {
    groupCode: "D",
    block: "EFFICIENCY",
    code: "competitionParticipants",
    label: "Участники соревнований",
    unit: "чел.",
    benchmarkMax: 600,
    weight: 0.3,
    inputMode: "number",
    helpText: "Суммарное число участников соревнований.",
    autoCalculated: false,
  },
  {
    groupCode: "D",
    block: "QUALITY",
    code: "satisfaction",
    label: "Удовлетворённость",
    unit: "балл",
    benchmarkMax: 5,
    weight: 0.5,
    inputMode: "satisfaction",
    helpText: "Средняя оценка до 5 баллов.",
    autoCalculated: false,
  },
  {
    groupCode: "D",
    block: "QUALITY",
    code: "sportsCoveragePct",
    label: "Спортивный охват",
    unit: "%",
    benchmarkMax: 25,
    weight: 0.3,
    inputMode: "percent",
    helpText: "Доля населения, вовлечённого в спортпрограммы.",
    autoCalculated: false,
  },
  {
    groupCode: "D",
    block: "QUALITY",
    code: "coveragePct",
    label: "Охват населения",
    unit: "%",
    benchmarkMax: 25,
    weight: 0.2,
    inputMode: "percent",
    helpText: "Авто: посещаемость ÷ численность в зоне × 100.",
    autoCalculated: true,
  },
];

export function getTemplatesForGroup(groupCode: string): CriterionTemplate[] {
  return SCORING_TEMPLATES.filter((t) => t.groupCode === groupCode);
}

export function getTemplateByCode(
  groupCode: string,
  code: string,
): CriterionTemplate | undefined {
  return SCORING_TEMPLATES.find((t) => t.groupCode === groupCode && t.code === code);
}
